### ISSUE TITLE
Migration to version 14.0

### ISSUE THREAD

**Issue by kaynnan** [Escodoo/weni-addons#73]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

# Modules to migrate

- [ ] base_automation_webhook
- [ ] weni_account_custom
- [ ] weni_contacts_custom
- [ ] weni_contract_consumption
- [ ] weni_contract_consumption_integration
- [ ] weni_contract_mis_builder_cash_flow
- [ ] weni_crm_custom
- [ ] weni_hr_contract_custom
- [ ] weni_hr_custom
- [ ] weni_mail_custom
- [ ] weni_mis_builder_cash_flow_custom
- [ ] weni_partner_mrr_calculation
- [ ] weni_partner_nps
- [ ] weni_platform_integration
- [ ] weni_product_contract_custom
- [ ] weni_project_custom
- [ ] weni_sale_custom
- [ ] weni_sale_invoice_plan_custom
- [ ] weni_sale_invoice_plan_mis_builder_cash_flow

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
